# AnyCPU will produce x64 for NotakeyNETProvider,
# which is the only project that has a bit-dependency
# (due to the version of credentialprovider_*.dll reference)
platform: Any CPU
configuration: Debug

before_build:
  - nuget restore
install:
  - git submodule update --init --recursive
build:
  project: NotakeyNETProvider.sln
artifacts:
  - path: 'register*.bat'
  - path: 'unregister*.bat'
  - path: '**\*.reg'
  - path: NotakeyNETProvider\bin\x64\$(configuration)
    name: 'NotakeyNETProvider'
  - path: NotakeyBGService\bin\$(configuration)
    name: 'NotakeyBGService'
  - path: CredUIInvokerNET\bin\$(configuration)
    name: 'CredUIInvokerNET'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

