platform: Any CPU
# configuration: Release
before_build:
  - nuget restore
install:
  - git submodule update --init --recursive
build:
  project: NotakeyNETProvider.sln
artifacts:
  - path: '**\*.bat'
  - path: '**\*.reg'
  - path: NotakeyNETProvider\bin\$(configuration)
    name: 'NotakeyNETProvider'
  - path: NotakeyBGService\bin\$(configuration)
    name: 'NotakeyBGService'
  - path: CredUIInvokerNET\bin\$(configuration)
    name: 'CredUIInvokerNET'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

